name: CI
on: 
  workflow_dispatch:
 
jobs:
 build:
    # runs-on: ubuntu-latest
    runs-on: ubuntu-22.04
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v2
      - name: Setup App
        working-directory: ./runner
        run: |
            echo OK
